spring.application.name=appointment


##############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip = ${DB_IP:localhost}
database.port = ${DB_PORT:5432}
database.user = ${DB_USER:postgres}
database.password = ${DB_PASSWORD:admin}
database.name = ${DB_DBNAME:appointment_db}

spring.sql.init.platform=postgres
spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

#spring.main.allow-circular-references = true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
server.tomcat.threads.max = 1
###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=info
logging.level.org.springframework=info
logging.level.ro.tuc=info

#spring.kafka.producer.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.port=${PORT:8080}

##################################################################################################################
### TESTING PROPERTIES ###
##################################################################################################################

#spring.application.name=appointment
#
#
###############################################
#### DATABASE CONNECTIVITY CONFIGURATIONS ###
################################################
#database.ip = ${DB_IP:localhost}
#database.port = ${DB_PORT:5432}
#database.user = ${DB_USER:postgres}
#database.password = ${DB_PASSWORD:admin}
#database.name = ${DB_DBNAME:appointment_db}
#
#spring.sql.init.platform=postgres
#spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
#spring.datasource.username = ${database.user}
#spring.datasource.password = ${database.password}
#
##spring.main.allow-circular-references = true
#
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.show_sql=true
#server.tomcat.threads.max = 1
################################################
#### LOGGING CONFIGURATIONS ###
################################################
#logging.level.root=info
#logging.level.org.springframework=info
#logging.level.ro.tuc=info
#
##spring.kafka.producer.bootstrap-servers=localhost:9092
##spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
##spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#
#
################################################
#### EMBEDDED TOMCAT CONFIGURATIONS ###
################################################
#server.port=${PORT:8084}